version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: ember-template-lint
    versions:
    - 3.0.0
    - 3.0.1
    - 3.1.0
    - 3.1.1
    - 3.2.0
  - dependency-name: eslint-plugin-ember
    versions:
    - 10.1.2
    - 10.2.0
    - 10.3.0
    - 10.4.1
  - dependency-name: ember-cli
    versions:
    - 3.25.3
  - dependency-name: "@clark/eslint-config-ember"
    versions:
    - 2.0.0
    - 2.1.0
